apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: featuremap-pvc
  namespace: featuremap
  labels:
    app: featuremap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
