apiVersion: v1
kind: Service
metadata:
  name: featuremap
  namespace: featuremap
  labels:
    app: featuremap
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: featuremap
