apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: featuremap
  namespace: featuremap
  labels:
    app: featuremap
spec:
  rules:
    - host: featuremap.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: featuremap
                port:
                  number: 3000
